#შექმენით პროგრამა რომელსაც შეეძლება დიალოგი თქვენთან (აირჩიეთ ნებისმიერი თემა) input გამოყენებით
print("hello!")
hello = input(": ")
print("how old are you?")
age = input(": ")
print("where are you from?")
country = input(": ")
print("do you have brother or sister?")
siblings = input(": ")
print("whats your favourite food?")
food = input(": ")
print("do you like reading books?")
reading = input(": ")
print("do you play video games and wich ones?")
video_games = input(": ")
print("how many languages do you speak and wich ones?")
languages = input(": ")